### ISSUE TITLE
Invalid argument

### ISSUE THREAD

**Issue by ZherebcovSergey** [Instrumental/instrumental_agent-php#3]
I got this error when there is no access to the collector.instrumentalapp.com service.

> FastCGI sent in stderr: "PHP message: [2018-04-02 10:52:30] instrumental.ERROR: Exception caught: Argument 2 passed to Monolog\Logger::warn() must be of the type array, string given, called in .../php/vendor/instrumental/instrumental_agent/lib/Agent.php on line 440 #0 .../php/vendor/instrumental/instrumental_agent/lib/Agent.php(440): Monolog\Logger->warn('Couldn't resolv...', 'warn') #1 ../php/vendor/instrumental/instrumental_agent/lib/Agent.php(64): Instrumental\Agent->ipv4_address_for_host('collector.instr...', 8000) #2 .../php/vendor/instrumental/instrumental_agent/lib/Agent.php(333): Instrumental\Agent->connect() #3 .../php/vendor/instrumental/instrumental_" while reading response header from upstream,...

**Comment by jason-o-matic** [comment]
It looks like there was an error with logging the original exception. We've fixed this masking issue in v1.0.2 which we just released. Can you try updating to this newest version and giving it another shot? If it still errors this should give a better error message.
